services:
  ElsaDatabase:
    image: mysql:8.0
    container_name: elsa-database
    ports:
      - "30306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: elsa_database
      MYSQL_USER: elsa_user
      MYSQL_PASSWORD: elsa_pass
